#!/bin/sh
# /etc/profile
# vi:ft=sh

# Set our umask
umask 022

# Append our default paths
appendpath () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}

appendpath '/usr/local/sbin'
appendpath '/usr/local/bin'
appendpath '/usr/bin'
unset appendpath

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
# export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"

export PATH

# Load profiles from /etc/profile.d
for profile in /etc/profile.d/*.sh; do
	[ -r "$profile" ] && . "$profile"
done
unset profile

# Termcap is outdated, old, and crusty, kill it.
unset TERMCAP

# Man is much better than us at figuring this out
unset MANPATH
