#!/bin/sh

LINES=50

case $(file --mime-type "$1" -bL) in
    audio/*) 
        mediainfo "$1" | pygmentize -f terminal -l make
        # mediainfo "$1" | pygmentize -l yaml
        ;;
    video/*) 
        mediainfo "$1" | pygmentize -f terminal -l make
        # if ps a | grep "mpv --profile=lfprev"; then
        #     kill "$(ps a | \grep -i '[m]pv --profile=lfprev' | awk '{print $1}')"
        #     mpv --profile=lfprev "$1"
        # else
        #     mpv --profile=lfprev "$1"
        # fi
        ;;
    image/*)
        img2txt "$1"
        ;;
    application/pdf) 
        pdftotext "$1" -
        ;;
    application/zip) 
        zipinfo "$1"
        ;;
    application/zstd) 
        # zstdcat "$1" | head -n30
        tar -tvf "$1"
        ;;
    application/x-dosexec|inode/x-empty) 
        file -b "$1"
        ;;
    application/x-iso9660-image) 
        iso-info --no-header "$1"
        ;;
    application/vnd*) 
        # odt
        # pandoc "$1" -t markdown | highlight -O ansi --syntax markdown
        pandoc "$1" -t markdown | pygmentize -f terminal -l md
        ;;
    *) 
        case $1 in
            *.tar.gz) 
                tar -ztvf "$1"
                ;;
            *.tar.bz2) 
                tar -jtvf "$1"
                ;;
            *.tar.xz) 
                tar -tvf "$1"
                ;;
            *.xz) 
                xzcat "$1"
                ;;
            *.tar) 
                tar -tvf "$1"
                ;;
            *.7z|*.rar) 
                7z l "$1"
                ;;
            *.log*) 
                cat "$1"
                ;;
            *.X*) 
                pygmentize -f terminal -l xorg.conf "$1"
                ;;
            *) 
                pygmentize -f terminal -g "$1"
                ;;
        esac
        ;;
esac
