#!/bin/sh

LINES=50

HIGHLIGHT_THEME="$HOME/.cache/wal/pywal.theme"
HIGHLIGHT_CMD="highlight -O ansi -s $HIGHLIGHT_THEME"
PYGMENTIZE_CMD="pygmentize -f terminal"

# kitty +kitten icat --transfer-mode file --clear

case $1 in
    *.md|*.sh|*.ini|*.js)
        $HIGHLIGHT_CMD "$1"
        ;;
    *.c*nf*|*.cfg)
        $HIGHLIGHT_CMD --syntax ini "$1"
        ;;
    *.txt)
        $HIGHLIGHT_CMD --syntax md "$1"
        ;;
    *BUILD|*.bash*)
        $HIGHLIGHT_CMD --syntax sh "$1"
        ;;
    *.*patch)
        $HIGHLIGHT_CMD --syntax patch "$1"
        ;;
    *.python*)
        $HIGHLIGHT_CMD --syntax python "$1"
        ;;
    # *.zsh*)
    #     $HIGHLIGHT_CMD --syntax zsh "$1"
    #     ;;
    *.tar.gz|*.tgz)
        # tar -ztvf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        tar -ztf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.gz)
        gzip -l "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        # gzip -l "$1" | $HIGHLIGHT_CMD --syntax ls
        ;;
    *.tar.bz2)
        # tar -jtvf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        tar -jtf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.tar.xz)
        # tar -tvf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        tar -tf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.xz)
        xzcat "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.tar)
        tar -tvf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.7z|*.rar)
        7z l "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
        ;;
    *.log*)
        head -n$LINES "$1" | $PYGMENTIZE_CMD -l logtalk
        ;;
    *.res)
        head -n$LINES "$1" | $HIGHLIGHT_CMD --syntax json
        ;;
    *.Xauth*)
        hexdump -C "$1" | head -n$LINES | $PYGMENTIZE_CMD -l hexdump
        ;;
    *.X*)
        head -n$LINES "$1" | $PYGMENTIZE_CMD -l xorg.conf
        ;;
    *.git*)
        head -n$LINES "$1" | $PYGMENTIZE_CMD -l lsl
        ;;
    *)
        case $(file --mime-type "$1" -bL) in
            audio/*)
                mediainfo "$1" | $PYGMENTIZE_CMD -l make
                ;;
            video/*)
                ffmpegthumbnailer -i "$1" -o /tmp/ffmpegthumbnailer.png
                chafa -c 256 /tmp/ffmpegthumbnailer.png
                mediainfo "$1" | $PYGMENTIZE_CMD -l make
                ;;
            image/svg+xml|text/x-shellscript)
                $HIGHLIGHT_CMD "$1"
                ;;
            text/x-asm)
                $HIGHLIGHT_CMD --syntax asm "$1"
                ;;
            image/*)
                chafa -c 256 "$1"
                # kitty +kitten icat --transfer-mode file --place 80x40@88x1 --silent "$1"
                # ueberview "$1"
                mediainfo "$1" | $PYGMENTIZE_CMD -l make
                ;;
            application/pdf)
                pdftotext "$1" -
                ;;
            application/zip)
                zipinfo "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
                ;;
            application/zstd)
                # zstdcat "$1" | head -n30
                tar -tf "$1" | head -n$LINES | $PYGMENTIZE_CMD -l lsl
                ;;
            inode/symlink)
                file -b "$1"
                ;;
            application/x-dosexec|inode/*)
                file -b "$1"
                hexdump -C "$1" | head -n$LINES | $PYGMENTIZE_CMD -l hexdump
                ;;
            application/x-iso9660-image)
                iso-info --no-header "$1"
                hexdump -C "$1" | head -n$LINES | $PYGMENTIZE_CMD -l hexdump
                ;;
            # odt
            application/vnd.oasis.*)
                pandoc "$1" -t markdown | $HIGHLIGHT_CMD --syntax markdown
                ;;
            application/octet-stream)
                hexdump -C "$1" | head -n$LINES | $PYGMENTIZE_CMD -l hexdump
                # hexdump -C "$1" | $PYGMENTIZE_CMD -l hexdump
                ;;
            application/json)
                head -n$LINES "$1" | $HIGHLIGHT_CMD --syntax json
                ;;
            application/csv)
                head -n$LINES "$1" | $HIGHLIGHT_CMD --syntax c
                ;;
            application/*|text/x-bytecode*)
                file -b "$1"
                echo "-----------------------------------------------------------------------------"
                hexdump -C "$1" | head -n$LINES | $PYGMENTIZE_CMD -l hexdump
                ;;
            *)
                # nvimpager -c "$1"
                head -n$LINES | $PYGMENTIZE_CMD -g "$1"
                # $PYGMENTIZE_CMD -g "$1" || sudo $PYGMENTIZE_CMD -g "$1"
                ;;
        esac
        ;;
esac
