backend = "thumb"   # full resized fastresize kmeans thumb wal
color_space = "lab" # lab labmixed lch lchmixed lchansi
env_vars = true

# dark:            8 dark colors, dark background and light contrast
# harddark:        Same as `dark` with hard hue colors
# ansidark:        This is not a 'dark' variant, is a new palette that is meant to work with `lchansi` colorspace, which will maintain 'tty' like color order and only adjusting the colors acording to the theme. A possible solution for LS_COLORS and the like. Should workout with other colorspace, but the result may not be optimal
# softdark:        Variant of softlight, uses the lightest colors and a dark background (could be interpreted as `dark` inversed)
# light:           Light bg, dark fg
# softlight:       Light with soft pastel colors, counterpart of `harddark`
#
# dark16:          Same as `dark` but uses the 16 colors trick
# ansidark16:      The ansidark palette with 16 color variation
# harddark16:      Harddark with 16 color variation
# softdark16:      softdark with 16 color variation
#
# light16:         Same as `light` but uses the 16 color trick
# softlight16:     softlight with 16 color variation
#
# darkcomp:        This is a `dark` variant that changes all colors to it's complementary counterpart, giving the feeling of a 'new palette' but that still makes sense with the image provided
# harddarkcomp:    complementary colors variation of harddark scheme
# softdarkcomp:    complementary variation for softdark
# lightcomp:       complementary colors variation of light
# softlightcomp:   softlight with complementary colors
#
# darkcomp16:      16 variation of the dark complementary variant
# harddarkcomp16:  complementary colors variation of harddark scheme
# softdarkcomp16:  complementary variation for softdark with the 16 color variation
#
# lightcomp16:     complementary colors variation of light with the 16 color variation
# softlightcomp16: softlight with complementary colors with 16 colors
palette = "dark16"

check_contrast = true

# threshold = 25

saturation = 50

[templates]
colors = { src = 'colors', dst = '~/.cache/wal/colors' }

# Languages
sh   =    { src = 'colors.sh',   dst = '~/.cache/wal/colors.sh' }
py   =    { src = 'colors.py',   dst = '~/.cache/wal/colors.py' }
json =    { src = 'colors.json', dst = '~/.cache/wal/colors.json' }
hypr =    { src = 'colors.hypr', dst = '~/.cache/wal/colors.hypr' }
vim  =    { src = 'colors.vim',  dst = '~/.cache/wal/colors.vim' }

# Window Manager Things
dunst  = { src = 'dunst',      dst = '~/.config/dunst/dunstrc' }
mako   = { src = 'mako',       dst = '~/.config/mako/config' }
fuzzel = { src = 'fuzzel.ini', dst = '~/.config/fuzzel/fuzzel.ini' }
waybar = { src = 'waybar.css', dst = '~/.config/waybar/colors.css' }

# Terminals
kitty = { src = 'kitty',    dst = '~/.cache/wal/colors-kitty.conf' }
foot  = { src = 'foot.ini', dst = '~/.config/foot/foot.ini' }

zathura = { src = 'colors.zathurarc', dst = '~/.config/zathura/colors-zathura' }

# GUI Overlays
mpv = { src = 'mpv.conf', dst = '~/.config/mpv/colors.conf' }
mangohud = { src = 'mangohud', dst = '~/.config/MangoHud/MangoHud.conf', pywal = true }

gmmk = { src = 'gmmk', dst = '~/.cache/wal/gmmk', pywal = true }

tridactyl = { src = 'tridactyl.css', dst = '~/.config/tridactyl/themes/wal.css', pywal = true }

discord.src = '../../../src/wal-vencord/colors-discord.css'
discord.dst = '~/.config/vesktop/themes/wal-vencord.theme.css'
discord.pywal = true

# glava =   { src = 'glava.glsl', dst = '~/.config/glava/rc.glsl' }
# res =     { src = 'xres',       dst = '~/.config/Xresources' }

# pywal = { src = "~/.config/wal/templates/", dst = '~/.cache/wal/', pywal = true }
