backend = "full" # full resized kmeans thumb wal
color_space = "labmixed" # lab labmixed lch lchmixed lchansi
env_vars = true

saturation = 70
palette = "dark16"
check_contrast = true
# threshold = 25

[templates]
dunst.src = 'dunst'
dunst.dst = '~/.config/dunst/dunstrc'

mako.src = 'mako'
mako.dst = '~/.config/mako/config'

zathura.src = 'colors.zathurarc'
zathura.dst = '~/.config/zathura/colors-zathura'

hypr.src = 'colors.hypr'
hypr.dst = '~/.cache/wal/colors.hypr'

kitty.src = 'kitty'
kitty.dst = '~/.cache/wal/colors-kitty.conf'

gmmk.src = 'gmmk'
gmmk.dst = '~/.cache/wal/gmmk'
gmmk.pywal = true

discord.src = '/home/ty/src/pywal-vencord/colors-discord.css'
discord.dst = '~/.config/vesktop/themes/wal-vencord.theme.css'
discord.pywal = true

# glava =   { src = 'glava.glsl', dst = '~/.config/glava/rc.glsl' }
# res =     { src = 'xres',       dst = '~/.config/Xresources' }

# pywal = { src = "~/.config/wal/templates/", dst = '~/.cache/wal/', pywal = true }
